spring:
  application:
    name: Authentication
  profiles:
    active: prod
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:certs/publicKey.pem
  datasource:
    url: jdbc:mysql://localhost:3306/ram
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  main:
    allow-bean-definition-overriding: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always  #never, always
    threadPool:
      threadCount: 5
      threadPriority: 5
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler

rapid:
  baseURL: https://cricbuzz-cricket.p.rapidapi.com/
  urls:
    teams: teams/v1/
    series: series/v1/
    matchDetailsUrl: series/v1/
    leanback: mcenter/v1/
    matches: matches/v1/  #live|recent|upcoming as params
    scoreCard: /mcenter/v1/  #matchId/hscard this is the full url

cloud:
  aws:
    s3:
      region: us-east-1
      auto: false
    stack:
      auto: false

jwt:
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem
access:
  rsa-private-key: classpath:certs/accessToken/privateKey.pem
  rsa-public-key: classpath:certs/accessToken/publicKey.pem

server:
  port: 8089


logging:
  level:
    org:
      springframework:
        security: trace
aws:
  s3:
    bucket: progrowwuserimage
    access-key: dummy-aws-access-key
    secret-access-key: dummy-aws-secret-access-key
    region: us-east-1
