server:
  port: 8084
spring:
  application:
    name: cricket-service
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:mysql://localhost:3306/ram
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always  #never, always
    threadPool:
      threadCount: 5
      threadPriority: 5
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler

rapid:
  baseURL: https://cricbuzz-cricket.p.rapidapi.com/
  urls:
    teams: teams/v1/
    series: series/v1/
    matchDetailsUrl: series/v1/
    leanback: mcenter/v1/
    matches: matches/v1/  #live|recent|upcoming as params
    scoreCard: /mcenter/v1/  #matchId/hscard this is the full url

jwt:
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/ # ${ EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:localhost}