spring:
  application:
    name: wallet-service
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:certs/publicKey.pem
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/ram}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:} #rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQL8Dialect


jwt:
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem


server:
  port: 8086