server:
  port: 8989


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/ # ${ EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:localhost}


spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      default-filters:
        - name: DedupeResponseHeader
          args:
            name: Access-Control-Allow-Origin
            strategy: RETAIN_FIRST
      globalcors:
        corsConfigurations:
          '[/**]': # This will apply CORS to all routes
            allowedOrigins: "http://127.0.0.1:5500"  # Add specific origin(s) here
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
      #            allowCredentials: true
      websocket:
        enabled: true
      routes:
        - id: jwt-authentication
          uri: lb://JWTAUTHENTICATION
          predicates:
            - Path=/auth/**
        - id: test-server
          uri: lb://TEST-SERVICE
          predicates:
            - Path=/test/**
        - id: mail-service
          uri: lb://MAIL-SERVICE
          predicates:
            - Path=/mail/**
        - id: cricket-service
          uri: lb://CRICKET-SERVICE
          predicates:
            - Path=/live-scores/**
        - id: webSocket-router
          uri: lb://CRICKET-SERVICE
          predicates:
            - Path=/api/cricket/**
        - id: question-service
          uri: lb://QUESTION-GENERATOR
          predicates:
            - Path=/ques/**
management:
  endpoints:
    web:
      exposure:
        include: health,info

        #logging:
        #  level:
        #    org.springframework: DEBUG

        #resilience4j:
        #  circuitbreaker:
        #    instances:
        #      serviceACircuitBreaker:
        #        register-health-indicator: true
        #        failure-probability: 0.5
        #        sliding-window-size: 10
        #        minimum-number-of-calls: 10
        #        wait-duration-in-seconds: 30s
        #        waitDurationInOpenState: 30s



        #          filters:
        #            name: CircuitBreacker
        #            args:
        #              name: serviceBCircuitBreaker
        #              fallBack: forward:/fallback/service-b
        #            - StripPrefix=1

        #    httpclient:
        #      wiretap: true  #// do not use into production or read the document https://docs.spring.io/spring-cloud-gateway/reference/4.1-SNAPSHOT/appendix.html
        #      default-filters:
        #        - name: JwtAuthenticationFilter
        #          args:
        #            timeoutDuration: 20s