server:
  port: 8345


spring:
  application:
    name: TEST-SERVICE
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:certs/publicKey.pem
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/ram}
    username: ${DATABASE_USERNAME:root}
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


jwt:
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/ # ${ EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:localhost}

management:
  endpoints:
    web:
      exposure:
        include: health, info